'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { t } from '@myclash/i18n';
import { useToast } from '@myclash/ui';

interface Ruleset {
  code: string;
  version: string;
  label: string;
}
interface PenaltyRuleset {
  id: string;
  name: string;
}

interface TournamentBasics {
  name: string;
  slug: string;
  weapon: string | null;
  rulesetCode: string;
  rulesetVersion: string;
  penaltyRulesetId: string | null;
  /** Slice 4: cap on registered + checked_in. Null = unlimited. */
  maxParticipants: number | null;
  /** Slice 4: cap on waitlist size. Null = unlimited. */
  maxWaitlist: number | null;
}

const apiUrl = process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:4000';

export function BasicsTab({ tournamentId }: { tournamentId: string }) {
  const params = useParams<{ slug: string }>();
  const orgSlug = params.slug;
  const toast = useToast();
  const [data, setData] = useState<TournamentBasics | null>(null);
  const [rulesets, setRulesets] = useState<Ruleset[]>([]);
  const [penaltyRulesets, setPenaltyRulesets] = useState<PenaltyRuleset[]>([]);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!orgSlug) return;
    // Resolve org id from slug so we can hit the org-scoped penalty-rulesets
    // endpoint (which filters out other orgs' public rulesets).
    void fetch(`${apiUrl}/api/v1/organizations/slug/${encodeURIComponent(orgSlug)}`, {
      credentials: 'include',
    })
      .then((r) => (r.ok ? r.json() : null))
      .then((org: { id: string } | null) => {
        const penaltyEndpoint = org
          ? `/api/v1/organizations/${org.id}/penalty-rulesets`
          : '/api/v1/penalty-rulesets';

        return Promise.all([
          fetch(`${apiUrl}/api/v1/tournaments/${tournamentId}`, { credentials: 'include' }).then(
            (r) => (r.ok ? r.json() : null),
          ),
          fetch(`${apiUrl}/api/v1/rulesets`, { credentials: 'include' }).then((r) =>
            r.ok ? r.json() : [],
          ),
          fetch(`${apiUrl}${penaltyEndpoint}`, { credentials: 'include' }).then((r) =>
            r.ok ? r.json() : [],
          ),
        ]).then(([row, r, p]) => {
          if (row) {
            setData({
              name: row.name,
              slug: row.slug,
              weapon: row.weapon,
              rulesetCode: row.ruleset_code,
              rulesetVersion: row.ruleset_version,
              penaltyRulesetId: row.penalty_ruleset_id,
              maxParticipants: row.max_participants ?? null,
              maxWaitlist: row.max_waitlist ?? null,
            });
          }
          setRulesets(r as Ruleset[]);
          setPenaltyRulesets(p as PenaltyRuleset[]);
        });
      });
  }, [tournamentId, orgSlug]);

  async function save() {
    if (!data) return;
    setSaving(true);
    try {
      const res = await fetch(`${apiUrl}/api/v1/tournaments/${tournamentId}`, {
        method: 'PATCH',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: data.name,
          weapon: data.weapon ?? undefined,
          rulesetCode: data.rulesetCode,
          rulesetVersion: data.rulesetVersion,
          penaltyRulesetId: data.penaltyRulesetId,
          maxParticipants: data.maxParticipants,
          maxWaitlist: data.maxWaitlist,
        }),
      });
      if (!res.ok) throw new Error('Save failed');
      toast.success(t('organizer.tournaments.settings.saved'));
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Error');
    } finally {
      setSaving(false);
    }
  }

  if (!data) return <p className="text-sm text-muted">{t('common.loading')}</p>;

  return (
    <div className="space-y-4">
      <h2 className="font-display font-semibold text-lg sm:text-xl text-foreground">
        {t('organizer.tournaments.settings.basics')}
      </h2>

      <Field label={t('organizer.tournaments.settings.name')}>
        <input
          value={data.name}
          onChange={(e) => setData({ ...data, name: e.target.value })}
          className="w-full rounded-md border border-border px-3 py-2 text-sm"
        />
      </Field>

      <label className="block">
        <span className="block text-xs font-medium text-foreground-secondary mb-1">
          {t('organizer.tournaments.settings.slug')}{' '}
          <span className="font-normal text-muted">
            {t('organizer.tournaments.wizard.slugAutoGenerated')}
          </span>
        </span>
        <input
          value={data.slug}
          disabled
          className="w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-muted font-mono"
        />
        <p className="text-xs text-muted mt-1">{t('organizer.tournaments.settings.slugLocked')}</p>
      </label>

      <Field label={t('organizer.tournaments.settings.weapon')}>
        <input
          value={data.weapon ?? ''}
          onChange={(e) => setData({ ...data, weapon: e.target.value || null })}
          className="w-full rounded-md border border-border px-3 py-2 text-sm"
        />
      </Field>

      <Field label={t('organizer.tournaments.settings.ruleset')}>
        <select
          value={`${data.rulesetCode}:${data.rulesetVersion}`}
          onChange={(e) => {
            const [code, version] = e.target.value.split(':');
            setData({ ...data, rulesetCode: code!, rulesetVersion: version! });
          }}
          className="w-full rounded-md border border-border px-3 py-2 text-sm"
        >
          {rulesets.map((r) => (
            <option key={`${r.code}:${r.version}`} value={`${r.code}:${r.version}`}>
              {r.label}
            </option>
          ))}
        </select>
      </Field>

      <label className="block">
        <span className="mb-1 flex items-center gap-1.5 text-xs font-medium text-foreground-secondary">
          {t('organizer.tournaments.settings.penaltyRuleset')}
          <span className="rounded bg-success/10 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-success">
            {t('organizer.tournaments.wizard.recommended')}
          </span>
        </span>
        <select
          value={data.penaltyRulesetId ?? ''}
          onChange={(e) => setData({ ...data, penaltyRulesetId: e.target.value || null })}
          className="w-full rounded-md border border-border px-3 py-2 text-sm"
        >
          <option value="">{t('common.none')}</option>
          {penaltyRulesets.map((p) => (
            <option key={p.id} value={p.id}>
              {p.name}
            </option>
          ))}
        </select>
        {!data.penaltyRulesetId && (
          <p className="mt-1 text-xs text-warning">
            {t('organizer.tournaments.wizard.penaltyRulesetBlankHint')}
          </p>
        )}
      </label>

      {/* Slice 4: capacity caps. Leaving either field blank means "no cap".
       *  When the participant cap is reached, the registrations create
       *  endpoint returns 409 and the admin UI offers an explicit
       *  'Add to waitlist instead?' confirmation. */}
      <Field label={t('admin.orgTournaments.maxParticipants')}>
        <input
          type="number"
          min={1}
          value={data.maxParticipants ?? ''}
          onChange={(e) =>
            setData({
              ...data,
              maxParticipants: e.target.value === '' ? null : Number(e.target.value),
            })
          }
          placeholder={t('admin.orgTournaments.noCap')}
          className="w-full rounded-md border border-border px-3 py-2 text-sm"
        />
      </Field>

      <Field label={t('admin.orgTournaments.maxWaitlist')}>
        <input
          type="number"
          min={0}
          value={data.maxWaitlist ?? ''}
          onChange={(e) =>
            setData({
              ...data,
              maxWaitlist: e.target.value === '' ? null : Number(e.target.value),
            })
          }
          placeholder={t('admin.orgTournaments.noCap')}
          className="w-full rounded-md border border-border px-3 py-2 text-sm"
        />
        {data.maxWaitlist != null && data.maxWaitlist > 0 && data.maxParticipants == null && (
          <p className="mt-1 text-xs text-warning">{t('admin.orgTournaments.waitlistNeedsCap')}</p>
        )}
      </Field>

      <button
        type="button"
        onClick={() => void save()}
        disabled={saving}
        className="rounded-md bg-accent px-4 py-2 text-sm font-semibold text-accent-foreground hover:bg-accent-hover disabled:opacity-50"
      >
        {saving ? t('common.saving') : t('organizer.tournaments.settings.save')}
      </button>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="block text-xs font-medium text-foreground-secondary mb-1">{label}</span>
      {children}
    </label>
  );
}
