/**
 * Matches, match events, and exchanges.
 * Exchange is the atomic scoring unit — the single source of truth for scores.
 */
import { boolean, integer, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { lices } from './events';
import { pools, registrations } from './tournaments';

// ── Matches ───────────────────────────────────────────────────────────────────
export const matches = pgTable('matches', {
  id: uuid('id').primaryKey().defaultRandom(),
  phaseId: uuid('phase_id').notNull(),
  poolId: uuid('pool_id').references(() => pools.id, { onDelete: 'set null' }),
  bracketSlotId: uuid('bracket_slot_id'),
  liceId: uuid('lice_id').references(() => lices.id, { onDelete: 'set null' }),
  redRegistrationId: uuid('red_registration_id').references(() => registrations.id, {
    onDelete: 'restrict',
  }),
  blueRegistrationId: uuid('blue_registration_id').references(() => registrations.id, {
    onDelete: 'restrict',
  }),
  scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
  startedAt: timestamp('started_at', { withTimezone: true }),
  endedAt: timestamp('ended_at', { withTimezone: true }),
  durationActiveMs: integer('duration_active_ms'),
  durationTotalMs: integer('duration_total_ms'),
  // Derived scores — materialized for fast reads, always recomputed from exchanges
  redScore: integer('red_score').notNull().default(0),
  blueScore: integer('blue_score').notNull().default(0),
  winnerRegistrationId: uuid('winner_registration_id').references(() => registrations.id, {
    onDelete: 'set null',
  }),
  status: text('status').notNull().default('scheduled'),
  // scheduled | running | paused | completed | voided
  scorekeeperUserId: uuid('scorekeeper_user_id'),
  rulesetCode: text('ruleset_code').notNull().default('TF_v1'),
  rulesetVersion: text('ruleset_version').notNull().default('1'),
  matchNumberLabel: text('match_number_label'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Match events (timeline) ───────────────────────────────────────────────────
export const matchEvents = pgTable('match_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  matchId: uuid('match_id')
    .notNull()
    .references(() => matches.id, { onDelete: 'cascade' }),
  sequence: integer('sequence').notNull(),
  type: text('type').notNull(),
  // start | halt | resume | warning | end | reset_clock
  reason: text('reason'),
  byUserId: uuid('by_user_id'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Exchanges ─────────────────────────────────────────────────────────────────
// THE source of truth. Scores are always derived from non-voided exchanges.
// Never store computed scores as the source of truth (AGENTS.md hard rule #1).
export const exchanges = pgTable('exchanges', {
  id: uuid('id').primaryKey().defaultRandom(),
  // client_uuid: idempotency key generated by the scoring tablet.
  // Server inserts are idempotent on this UUID — offline-first safety.
  clientUuid: uuid('client_uuid').notNull().unique(),
  matchId: uuid('match_id')
    .notNull()
    .references(() => matches.id, { onDelete: 'cascade' }),
  sequence: integer('sequence').notNull(),
  type: text('type').notNull(),
  // clean | afterblow | double | no_exchange
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
  recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
  durationSincePrevMs: integer('duration_since_prev_ms'),
  firstStrikerColor: text('first_striker_color'), // 'red' | 'blue' | null
  firstStrikeValue: integer('first_strike_value'), // 1 | 2 | null
  afterblowValue: integer('afterblow_value'), // 1 | 2 | null
  noExchangeReason: text('no_exchange_reason'),
  // Materialized deltas for fast aggregation (always recomputable from type+values)
  redScoreDelta: integer('red_score_delta').notNull().default(0),
  blueScoreDelta: integer('blue_score_delta').notNull().default(0),
  voided: boolean('voided').notNull().default(false),
  voidedReason: text('voided_reason'),
});
