/**
 * The write routes the archived-Event lock does not place, each filed under why.
 *
 * Read by `common/event-readonly/archived-lock.routes.test.ts`, which fails on a
 * write route that the resolver (`common/event-readonly/resolve-event-id.ts`)
 * cannot place, that carries no `@AllowOnArchivedEvent()`, and that no list
 * here names. A line is a route as `VERB path`, the path without the global
 * prefix. Test-only, with the rest of `common/testing/` (ruling 222).
 */

/** They write no row of one Event. */
export const NOT_EVENT_OWNED: Readonly<Record<string, readonly string[]>> = {
  'Platform administration: backups, accounts, organisations, AI keys and budget, flags, data quality, system status.':
    [
      'DELETE admin/ai-keys/:id',
      'DELETE admin/backups',
      'DELETE admin/backups/:backupId',
      'DELETE admin/organizations/:id',
      'DELETE admin/users/:id',
      'DELETE admin/users/:id/organizations/:orgId',
      'DELETE admin/users/:id/platform-role',
      'DELETE admin/users/:id/temp-password',
      'PATCH admin/ai-keys/:id',
      'PATCH admin/ai-settings/budget',
      'PATCH admin/data-quality/findings/:id',
      'PATCH admin/data-retention',
      'PATCH admin/organizations/:id',
      'PATCH admin/organizations/:id/approve',
      'PATCH admin/organizations/:id/reactivate',
      'PATCH admin/organizations/:id/suspend',
      'PATCH admin/query-errors/:id/resolve',
      'PATCH admin/users/:id',
      'PATCH admin/users/:id/disable',
      'PATCH admin/users/:id/enable',
      'PATCH admin/users/:id/organizations/:orgId',
      'POST admin/ai-keys',
      'POST admin/ai-keys/:id/activate',
      'POST admin/ai-keys/:id/model-sync',
      'POST admin/ai-settings/model-sync',
      'POST admin/backups/run',
      'POST admin/backups/upload',
      'POST admin/data-quality/scans',
      'POST admin/organizations',
      'POST admin/organizations/:id/reassign-owner',
      'POST admin/system-versions/components/:key/:action',
      'POST admin/system/tls-status/renew',
      'POST admin/users',
      'POST admin/users/:id/organizations',
      'POST admin/users/:id/regenerate-temp-password',
      'POST admin/users/:id/send-password-reset',
      'PUT admin/backups/schedule',
      'PUT admin/feature-flags/:key',
      'PUT admin/system/runtime-health/alert-settings',
      'PUT admin/users/:id/platform-role',
    ],
  'Shared libraries an Event points at (rulesets, scoring systems, weapons, clubs, venues, pay plans). Deleting a club or a venue clears its link in an archived Event too (ON DELETE SET NULL).':
    [
      'DELETE admin/custom-rulesets/:id',
      'DELETE admin/league-scoring-systems/:id',
      'DELETE admin/weapons/:id',
      'DELETE clubs/:id',
      'DELETE clubs/:id/logo',
      'DELETE compensation-plans/:planId',
      'DELETE organizations/:orgId/custom-rulesets/:id',
      'DELETE penalty-rulesets/:id',
      'DELETE venue-areas/:areaId',
      'DELETE venue-lices/:liceId',
      'DELETE venues/:venueId',
      'PATCH admin/custom-rulesets/:id',
      'PATCH admin/league-scoring-systems/:id',
      'PATCH admin/league-scoring-systems/:id/set-default',
      'PATCH admin/weapons/:id',
      'PATCH clubs/:id',
      'PATCH clubs/:id/unverify',
      'PATCH clubs/:id/verify',
      'PATCH compensation-plans/:planId',
      'PATCH organizations/:orgId/custom-rulesets/:id',
      'PATCH penalty-rulesets/:id',
      'PATCH venue-areas/:areaId',
      'PATCH venues/:venueId',
      'POST admin/custom-rulesets',
      'POST admin/custom-rulesets/:id/approve-public',
      'POST admin/custom-rulesets/:id/clone',
      'POST admin/custom-rulesets/:id/publish',
      'POST admin/custom-rulesets/:id/reject-submission',
      'POST admin/custom-rulesets/:id/set-default',
      'POST admin/custom-rulesets/:id/unpublish',
      'POST admin/custom-rulesets/:id/versions/:versionId/rollback',
      'POST admin/custom-rulesets/validate',
      'POST admin/league-scoring-systems',
      'POST admin/league-scoring-systems/:id/clone',
      'POST admin/league-scoring-systems/:id/versions/:versionId/rollback',
      'POST admin/weapons',
      'POST clubs',
      'POST clubs/:id/logo',
      'POST clubs/bulk-archive',
      'POST clubs/bulk-cleanup-delete',
      'POST clubs/bulk-delete',
      'POST clubs/bulk-unverify',
      'POST clubs/bulk-update',
      'POST clubs/bulk-verify',
      'POST organizations/:orgId/compensation-plans',
      'POST organizations/:orgId/custom-rulesets',
      'POST organizations/:orgId/custom-rulesets/:id/submit',
      'POST organizations/:orgId/custom-rulesets/fork',
      'POST organizations/:orgId/custom-rulesets/import',
      'POST organizations/:orgId/custom-rulesets/validate',
      'POST organizations/:orgId/penalty-rulesets/import',
      'POST organizations/:orgId/venues',
      'POST penalty-rulesets',
      'POST penalty-rulesets/:id/approve-sharing',
      'POST penalty-rulesets/:id/publish',
      'POST penalty-rulesets/:id/reject-sharing',
      'POST penalty-rulesets/:id/rollback',
      'POST penalty-rulesets/:id/submit-for-sharing',
      'POST venues/:venueId/areas',
      'POST venues/:venueId/lices',
      'PUT compensation-plans/:planId/role-rates',
      'PUT compensation-plans/:planId/tiers',
    ],
  "An organisation's own settings and members.": [
    'DELETE organizations/:id/members/:userId',
    'DELETE organizations/:orgId/ai-keys/:id',
    'PATCH organizations/:id',
    'PATCH organizations/:orgId/ai-keys/:id',
    'PATCH organizations/:orgId/ai-settings/budget',
    'PATCH organizations/:orgId/ai-settings/flags',
    'POST organizations',
    'POST organizations/:id/logo',
    'POST organizations/:id/members',
    'POST organizations/:orgId/ai-keys',
    'POST organizations/:orgId/ai-keys/:id/activate',
  ],
  'A new Event, created or restored from an archive.': [
    'POST archive/restore-preview',
    'POST organizations/:orgId/events',
  ],
  "Leagues' own rows: leagues, groups, roles, links and requests.": [
    'DELETE admin/league-groups/:groupId',
    'DELETE admin/leagues/:leagueId',
    'DELETE admin/leagues/:leagueId/logo',
    'DELETE admin/leagues/:leagueId/organization-roles/:organizationId',
    'DELETE admin/leagues/:leagueId/user-roles/:targetUserId',
    'PATCH admin/league-groups/:groupId',
    'PATCH admin/league-membership-requests/:requestId',
    'PATCH admin/league-tournament-links/:linkId',
    'PATCH admin/leagues/:leagueId',
    'PATCH orgs/:orgId/league-requests/:requestId/withdraw',
    'POST admin/leagues',
    'POST admin/leagues/:leagueId/clone',
    'POST admin/leagues/:leagueId/finalize',
    'POST admin/leagues/:leagueId/groups',
    'POST admin/leagues/:leagueId/logo',
    'POST admin/leagues/:leagueId/organization-roles',
    'POST admin/leagues/:leagueId/recompute',
    'POST admin/leagues/:leagueId/reopen',
    'POST admin/leagues/:leagueId/user-roles',
    'POST orgs/:orgId/league-requests',
  ],
  "The people directory: global profiles and their ratings, not an Event's roster.": [
    'PATCH fighters/:id',
    'PATCH global-persons/:id',
    'POST admin/hema-ratings/fighters/:globalPersonId/refresh',
    'POST admin/hema-ratings/sync',
    'POST fighters',
    'POST global-persons',
    'POST global-persons/import',
    'POST global-persons/import/preview',
  ],
  "The caller's own account, session, follows, groups, keys and devices.": [
    'DELETE fighters/me/photo',
    'DELETE guest-sessions/me',
    'DELETE me/ai-keys/:id',
    'DELETE me/follows/by-global-person/:globalPersonId',
    'DELETE me/follows/organizations/:organizationId',
    'DELETE me/groups/:groupId',
    'DELETE me/groups/:groupId/members/:globalPersonId',
    'PATCH fighters/me/profile',
    'PATCH me/ai-keys/:id',
    'PATCH me/follows/by-global-person/:globalPersonId',
    'PATCH me/groups/:groupId',
    'PATCH notifications/preferences',
    'POST auth/logout',
    'POST auth/magic-link',
    'POST auth/public-password-reset',
    'POST auth/public-signup',
    'POST auth/signup',
    'POST fighters/me/photo',
    'POST me/ai-keys',
    'POST me/ai-keys/:id/activate',
    'POST me/change-password',
    'POST me/follows/by-global-person',
    'POST me/follows/organizations',
    'POST me/groups',
    'POST me/groups/:groupId/members',
    'POST me/insight/generate',
    'POST me/insight/publish',
    'POST me/insight/unpublish',
    'POST me/legal',
    'POST notifications/me/subscribe',
    'POST notifications/me/subscribed',
    'POST notifications/me/unsubscribe',
    'POST staff-auth/logout',
  ],
};

/** The lock reads the Event the body names (`body.eventId`), when it names one. */
export const PLACED_BY_BODY: readonly string[] = [
  'POST penalty-rulesets/import-csv',
  'POST referee-assignments',
];

/** Refused on an archived Event by another owner; each reason names the test that holds it. */
export const LOCKED_ELSEWHERE: Readonly<Record<string, readonly string[]>> = {
  'A Tournament restored into an existing Event: the restore refuses an archived one (ArchiveService.restoreTournamentCopy): archive.service.test.ts.':
    ['POST archive/restore'],
  'A staff session is refused once its Event is completed or archived (StaffService.requireStaffFromRequest and login): staff.service.event-over.test.ts.':
    [
      'POST staff-auth/login',
      'POST staff/checkin/:personId/arrive',
      'POST staff/checkin/:personId/undo',
      'POST staff/checkin/scan',
      'POST staff/gear/:personId/:weaponId',
      'POST staff/heartbeat',
    ],
};

/** They reach the rows of an archived Event, and must. */
export const OPEN_ON_PURPOSE: Readonly<Record<string, readonly string[]>> = {
  'A platform restore puts back the whole database, every Event at once.': [
    'POST admin/backups/restore',
  ],
  'Erasure and privacy: they reach every Event of a person, an archived one first.': [
    'DELETE me/account',
    'DELETE persons/me/email-change',
    'PATCH persons/me/privacy',
    'POST admin/data-retention/run',
    'POST admin/global-persons/:id/anonymise',
    'POST persons/me/email-change',
  ],
  'Identity: a sign-in, a claim, a promotion or a merge ties one person together across every Event they took part in (syncClaimedPersonRows, completeClaim).':
    [
      'DELETE me/global-person-link',
      'PATCH global-persons/:id/link-workshop-enrollment',
      'POST admin/global-person-claim-requests/:id/approve',
      'POST admin/global-person-claim-requests/:id/reject',
      'POST auth/oauth/session',
      'POST auth/password-login',
      'POST auth/public-login',
      'POST auth/public-password-reset-confirm',
      'POST fighters/:id/promote',
      'POST fighters/merge',
      'POST fighters/merge/:auditLogId/revert',
      'POST me/claim-confirm',
      'POST me/claim-persons',
      'POST me/global-person-claim',
    ],
  "A super admin's answer to a request filed about an Event; the review queue answers the same requests and carries @AllowOnArchivedEvent().":
    [
      'POST admin/exchange-edit-requests/:id/approve',
      'POST admin/exchange-edit-requests/:id/reject',
      'POST clubs/review-requests/:id/approve',
      'POST clubs/review-requests/:id/link',
      'POST clubs/review-requests/:id/reject',
    ],
};

/** They reach the rows of an archived Event and no ruling covers it. May only shrink. */
export const NAMED_OPEN: Readonly<Record<string, readonly string[]>> = {
  "AI text about an Event, a Tournament or a profile, shown on its page: no ruling says whether an archived Event's text may still be generated or published.":
    [
      'POST generated-content/:type/:entityId/generate',
      'POST generated-content/:type/:entityId/publish',
      'POST generated-content/:type/:entityId/unpublish',
    ],
};
